# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TaxiZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(db_index=True, unique=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('borough', models.CharField(blank=True, max_length=50)),
                ('lat', models.FloatField(default=40.73)),
                ('lon', models.FloatField(default=-73.99)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_type', models.CharField(db_index=True, max_length=10)),
                ('pickup_datetime', models.DateTimeField(db_index=True)),
                ('dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.FloatField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('pulocation_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dolocation_id', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.FloatField(blank=True, null=True)),
                ('fare_amount', models.FloatField(blank=True, null=True)),
                ('extra', models.FloatField(blank=True, null=True)),
                ('mta_tax', models.FloatField(blank=True, null=True)),
                ('tip_amount', models.FloatField(blank=True, null=True)),
                ('tolls_amount', models.FloatField(blank=True, null=True)),
                ('improvement_surcharge', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('congestion_surcharge', models.FloatField(blank=True, null=True)),
                ('airport_fee', models.FloatField(blank=True, null=True)),
                ('cbd_congestion_fee', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pickup_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='taxitrip',
            index=models.Index(fields=['cab_type', 'pickup_datetime'], name='dashboard_t_cab_typ_2d1e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxitrip',
            index=models.Index(fields=['cab_type', 'pulocation_id'], name='dashboard_t_cab_typ_3f4a2b_idx'),
        ),
    ]
